In [103]:
%matplotlib inline
import numpy as np
import fdmt

In [104]:
nf = 336
fmax = 1440.
fmin = fmax - nf*df
df = 1.0
nd = 1024
nt = 256
reload(fdmt)
thefdmt = fdmt.Fdmt(fmin, df, nf, nd, nt)


Iteration 1 2.0 2.0 2.0 False
Iteration 2 4.0 4.0 4.0 False
Iteration 3 8.0 8.0 8.0 False
Iteration 4 16.0 16.0 16.0 False
Iteration 5 32.0 32.0 16.0 True
Iteration 6 64.0 64.0 16.0 True
Iteration 7 128.0 128.0 80.0 False
Iteration 8 256.0 256.0 80.0 True
Iteration 9 336.0 512.0 336.0 False


In [105]:
thefdmt.hist_delta_t

[9, 18, 36, 71, 138, 265, 489, 847, 1023]

In [107]:
shapes = np.array(thefdmt.hist_state_shape)
print(shapes)

[[ 336    5  256]
 [ 168   10  266]
 [  84   19  275]
 [  42   37  293]
 [  21   72  328]
 [  11  139  395]
 [   6  266  522]
 [   3  490  746]
 [   2  848 1104]
 [   1 1024 1280]]


In [108]:
print(shapes.prod(axis=1), shapes.prod(axis=1).max())

(array([ 430080,  446880,  438900,  455322,  495936,  603955,  833112,
       1096620, 1872384, 1310720]), 1872384)


In [100]:
thefdmt.hist_nf_data[0][0]

(1104.0,
 1106.0,
 1104.5,
 1105.5,
 10,
 [(0, 0, 0, 0, (0, 0, 0), (0, 0, 0), (1, 0, 0)),
  (0, 0, 1, 0, (0, 1, 1), (0, 0, 1), (1, 0, 0)),
  (1, 1, 2, 0, (0, 2, 2), (0, 1, 2), (1, 0, 0)),
  (1, 1, 2, 1, (0, 3, 2), (0, 1, 2), (1, 1, 0)),
  (1, 1, 3, 1, (0, 4, 3), (0, 1, 3), (1, 1, 0)),
  (1, 1, 4, 1, (0, 5, 4), (0, 1, 4), (1, 1, 0)),
  (2, 2, 5, 1, (0, 6, 5), (0, 2, 5), (1, 1, 0)),
  (2, 2, 5, 2, (0, 7, 5), (0, 2, 5), (1, 2, 0)),
  (2, 2, 6, 2, (0, 8, 6), (0, 2, 6), (1, 2, 0)),
  (2, 2, 7, 2, (0, 9, 7), (0, 2, 7), (1, 2, 0))])

In [85]:
thefdmt._df_bot

512.0